### ISSUE TITLE
Expose styling to enable CSS overrides

### ISSUE THREAD

**Issue by ikeydoherty** [solus-project/mate-notification-theme-solus#2]
Convert the built-in theme to a fallback-theme so that Slate is effectively the CSS-themeable notification plugin for MATE Notification Daemon.

**Comment by flexiondotorg** [comment]
Ubuntu MATE will fund the development of this feature. The developer closing this issue with an commit accepted by upstream will receive $150 via PayPal.

**Comment by ikeydoherty** [comment]
Implemented, and @tista500 added support to Adapta. Releasing v5 now
